### ISSUE TITLE
Terracoin coin is slip44: 83

### ISSUE THREAD

**Issue by TheSin-** [trezor/trezor-common#126]
https://github.com/trezor/trezor-common/blob/55dc5c8f185a397d66fc0c63f39bdd32549fe040/defs/coins/terracoin.json#L21

as per https://github.com/satoshilabs/slips/blob/master/slip-0044.md

I just updated out core wallet to use 83 and it will be released shortly, wanted to see if we could get it updated here as well.

**Comment by prusnak** [comment]
Fixed in 7be980ae9651b990d497355a5978abb9a9d0d152
