### ISSUE TITLE
Stellar: modify _account fields to use addresses

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-common#135]
Fields such as destination_account currently accepts bytes (public key). It makes more sense to accept directly addresses (strings). It'll simplify the usage on the desktop side where the user usually works with addresses and not pubkeys.

https://github.com/trezor/trezor-common/blob/master/protob/messages.proto#L1091

**Comment by prusnak** [comment]
cc @zulucrypto

**Comment by prusnak** [comment]
@tsusanka Will you send a pull reuqest?

**Comment by tsusanka** [comment]
Yes, tomorrow though

**Comment by tsusanka** [comment]
Closed by https://github.com/trezor/trezor-common/commit/2f2888fba1962bdd13ff68ce7eb6467e45fe1985

**Comment by prusnak** [comment]
What is the standard length for Stellar addresses? 56-chars?

**Comment by tsusanka** [comment]
Yes, indeed.
