### ISSUE TITLE
Environment variable for protobuf include dir

### ISSUE THREAD

**Issue by ph4r05** [trezor/trezor-common#158]
When building protobuf messages via `setup.py` in python-trezor it would be great to specify protobuf include directory with environment variable, such as

```bash
export PROTOC_INCLUDE=/usr/local/include
```

It simplifies the setup for more complex projects

**Comment by saleemrashid** [comment]
The default might also be best specified as `os.path.join(os.path.dirname(os.path.dirname(distutils.spawn.find_executable("protoc"))), "include"))` or equivalent (e.g. `/usr/local/include` for `/usr/local/bin/protoc` or `/opt/protobuf/include`for `/opt/protobuf/bin/protoc`)
