### ISSUE TITLE
Remove Stellar's protobuf protocol_version field

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-common#159]
@zulucrypto what is the rational behind this field? https://github.com/trezor/trezor-common/blob/master/protob/messages.proto#L1664

I don't think it is being used anywhere

**Comment by zulucrypto** [comment]
@tsusanka - That line number doesn't look valid, could you give the line number or paste the field?

**Comment by tsusanka** [comment]
The protobuf messages usually change at the same time the code does, so we're not really doing some kind of backwards compatibility. @prusnak what do you think, can we remove this?

**Comment by prusnak** [comment]
Agree we should remove this, removed in 1ee1afd978390913e9cbfd9cea47624f2bc4e077
