### ISSUE TITLE
coin defs: address_prefix ending with ":"

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-common#165]
`build_coins.py` checks that the `address_prefix` fields ends with a semicolon (see https://github.com/trezor/trezor-common/blob/master/tools/build_coins.py#L105, https://github.com/trezor/trezor-common/blob/master/defs/coins/crown.json#L33)

That is a weird thing to enforce. ISTM the `address_prefix` should omit the semicolon and the check could instead match regex `^[a-z0-9]+$`, and calling code should add the semicolon.
(that is how `cashaddr_prefix` seems to behave)

**Comment by prusnak** [comment]
`address_prefix` is used solely in the web wallet, so this change has to be coordinated with the guys developing it.

I am not against the change and I think it makes sense.

**Comment by prusnak** [comment]
@mroz22 @mlejva can you please check where in webwallet/connect code do we use `address_prefix` and whether it is worth changing the logic (i.e. webwallet/connect adds the `:` character)

**Comment by mroz22** [comment]
In webWallet, it appears that address_prefix is used only for qr code parsing: 

https://github.com/satoshilabs/mytrezor/blob/e02b270ac5417ace6e6e675b0f80a7d4c10bc7c9/app/scripts/account/AccountSendCtrl.js#L521-L525

So from webwallet perspective it is easy to adapt to such change.

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/trezor-common/commit/c5045f066729dd3e650c3a61ec2dcfe01bccc8fa (where I renamed `address_prefix` to `uri_prefix`, because that's what it is and it will help us detect forgotten usage of this field).

@mroz22 please adapt the code in webwallet to use the `uri_prefix` field and add ":" at the end of the value
