### ISSUE TITLE
dust_limit for LTC is too high?

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-common#172]
According to coins definitions i shouldnt be able to sent LTC transaction lower than 0.00055 LTC.
I've tried to sign and push transaction with lower amount without validating dust limit and here is the result:

https://ltc-explorer.trezor.io/tx/761bbc4dd4ca619c7dd4c57a0a71e53a0ee7d4b1559a4c902277d6ca7c11df68

I've managed to push it with 0.00006 LTC.

So the question is: is this a bug/typo in coin definitions or there is some other reason why dust_limit for LTC is almost 10x bigger than in other coins?

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-common/commit/ee6897d153e5312f5f91c809eb1f2e8e2ae795b5
