### ISSUE TITLE
udev rule not working anymore

### ISSUE THREAD

**Issue by nomnombtc** [trezor/trezor-common#2]
Hi!

after this commit: https://github.com/trezor/trezor-common/commit/addadf367644245a10c8e9de7f33cfc0267d7a21

The udev rule does not work anymore under Slackware Linux, I needed to put back in:
MODE="0666", GROUP="dialout"

Greetings

**Comment by prusnak** [comment]
Argh, I am afraid that Slackware uses old udev which does not uses uaccess/udev-acl flags.

As Slackware is being used mainly by technical users I just added a note to the udev file (https://github.com/trezor/trezor-common/commit/fbcd1af05dab3f20dbef64178129a2ec0f1b8f5a).
