### ISSUE TITLE
Terracoin Contact Change Request & adding Official to Trezor

### ISSUE THREAD

**Issue by TheSin-** [trezor/trezor-common#235]
https://github.com/trezor/trezor-common/blob/8c53177626349e801757b0a1452a50ed72c51f27/defs/bitcoin/terracoin.json#L7

Could this be changed to ```"The Terracoin Foundation <support@terracoin.io>"```

Also I made a comment on https://github.com/trezor/trezor-common/pull/75 but since I can't reopen it I told a new ticket pointing it out would help?

This is the Quote from it...

Hi @prusnak I have been told that we have run into an issue here. I guess because we share addressing with bitcoin this isn't do able? We are 6 years old so changing our addressing isn't really something we are interested in, what are our other options to be supported by your project? Do I have to look at a masking like bch? I mean I'm not really keen on that either, but I'm just trying to make things work as I'd really like to get Trezor support with Terracoin. Please let me know your thought or anything I can do to make this possible.

**Comment by prusnak** [comment]
TRC contact changed in 8d7dd590ffe8c02a8d09aaefb7af41c11503f5a2

As I've said earlier, change the address version so it does not collide with Bitcoin and we might consider adding TRC to Trezor.

**Comment by prusnak** [comment]
You don't have to change any of the blockchain data. If you change address version, only the presentation of the data will change. I know this is a big change, maybe bigger your coin can handle, but it was a stupid decision not to change address version at the beginning in the first place.

**Comment by TheSin-** [comment]
I don't disagree but at the time there was only 16 coins in existence, I'm not sure if any of them knew back then that it wasn't a great idea.

I understand I can't change the chain data, that would be a disaster, but I do need to reset all the current addresses using the same private key to the new address, but that is still a MASSIVE change, not for the devel team (which is me), but to the entire community and infrastructure.

The worst being that exchanges like cryptopia don't support HFs anymore, and I can not see an easy way to Soft Fork this type of change easily.  I guess my only option is to consider it, but this will take a considerable amount of time to  change and likely a multiple release setup to do it, and all for only 1 HW (sadly my personal favourite), I haven't had any push back from others.  

Obviously vanity addresses are the ones that suffer the most, and some of our clients like have one address for BTC and TRC. 

Guess more internal discussion needs to happen, I just wanted to be 100% certain it was the only option.  Thanks for the consideration no matter what we decide.

**Comment by prusnak** [comment]
We have to rethink this. Maybe it would be possible to enable TRC on Trezor if we made coin name more visible in the device UI. Which is planned in the future.
