### ISSUE TITLE
[req] Allow use of other git services

### ISSUE THREAD

**Issue by baff5b** [trezor/trezor-common#262]
Hello,

Is it possible to use other Git services, like GitLab, when referencing the location for a coin's node source in a definition file? When initially testing, I saw that it would not validate : 
```
github: Value does not match regex ^https://github.com/.*[^/]$
```
when I used a gitlab link. It is possible to mirror the repository to GitHub, but I wanted to know if the repository can be referenced directly.

**Comment by matejcik** [comment]
that shouldn't be a problem, please send a PR with your gitlab value, I'll update the check

**Comment by prusnak** [comment]
Should work now
