### ISSUE TITLE
EOS Support

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/trezor-common#265]
We're nearing completion on implementation of EOS in our firmware, and I wanted to reiterate my offer to port that to the trezor-mcu codebase for T1 customers.

I want to gauge the level of interest in that, since as I understand it, SatoshiLabs folks intend on porting trezor-core to the T1, which ostensibly would get it EOS support once https://github.com/trezor/trezor-core/pull/397 lands. On the other hand, you've stated a few times that you are not generally accepting new coins to trezor-mcu... So whether or not this makes sense depends on your expected timeline for sunsetting the trezor-mcu codebase (which I assume is forthcoming), and whether you want EOS support for your T1 users in the interim.

Are you interested in such a PR?

**Comment by prusnak** [comment]
Yes, we are interested!

**Comment by matejcik** [comment]
moved here https://github.com/trezor/trezor-mcu/pull/449 (and closed there)
