### ISSUE TITLE
Minor: is regtest supported?

### ISSUE THREAD

**Issue by afk11** [trezor/trezor-common#270]
A while back some wallets changed the regtest bech32 prefix from 'tb' to 'bcrt'. This means that trezor will fail to accept the newer form (from bitcoin core, electrum, and other libraries)

I'm unsure if regtest is a desired network here, so opening this to get your opinion on it!

**Comment by afk11** [comment]
@slush0 @prusnak bump

tldr: regtest worked magically before, but broken now cuz everyone else has upgraded.

**Comment by prusnak** [comment]
We are following SLIP-0173: https://github.com/satoshilabs/slips/blob/master/slip-0173.md

If Bech32 prefix changed in the original implementation, that file is the place where the change should start.

**Comment by matejcik** [comment]
that document lists `bcrt` correctly though.
but to track that we'd need a separate entry in `defs/bitcoin` for bitcoin regrtest. i believe the original issue is about if we want that or not

**Comment by afk11** [comment]
@matejcik yes, I believe that would be necessary at this point since it's diverged from testnet.

**Comment by prusnak** [comment]
@afk11 Let's get this added. Please create a copy of `bitcoin_testnet.json` named `bitcoin_regtest.json` here:
https://github.com/trezor/trezor-firmware/blob/master/common/defs/bitcoin/
