### ISSUE TITLE
Block Explorers

### ISSUE THREAD

**Issue by thedevworks** [trezor/trezor-common#272]
It looks from the defs that BitCore or BlockBook are supported. What if I have a coin that has neither? Is this a required field for adding coin defs (Where Trezor interaction will be via Electrum)

**Comment by matejcik** [comment]
`bitcore` is a legacy field, going forward only Blockbook is going to be supported.

You need to have a blockbook backend if you want your coin to be available in the Trezor Wallet as a custom backend. Otherwise it's not necessary.
