### ISSUE TITLE
Nano support (for T1)

### ISSUE THREAD

**Issue by roosmaa** [trezor/trezor-common#274]
I'm currently in the process of contributing [Nano](https://nano.org/) [1] support to KeepKey. Since KeepKey is based on trezor-mcu it would be quite easy for me to port my work over. That is, if you guys are interested in it.

Relevant pull requests on the KeepKey repos:
- keepkey/trezor-crypto#1
- keepkey/keepkey-firmware#82
- keepkey/device-protocol#21
- keepkey/python-keepkey#47

[1] Nano is an fairly simple account based blockchain. It uses ed25519 with blake2b as the internal hashing function for it's key derivations and block signing.

**Comment by prusnak** [comment]
It would make sense for us to work on inclusion into [trezor-core](https://github.com/trezor/trezor-core) repo. This is currently used for Trezor Model T, but will eventually be available for Trezor One too.

**Comment by roosmaa** [comment]
Not familiar with the new trezor-core codebase, so not sure how much work that would be. Nor do I have a Model T to test my code on.

What about just upstreaming the trezor-crypto additions as the first step for the time being?

**Comment by prusnak** [comment]
Nah. I am not going to add stuff to trezor-crypto, unless it is going to be used.

**Comment by prusnak** [comment]
We don't want to add coins that do not belong to TOP 30 coins at the moment.
