### ISSUE TITLE
ICX (ICON) Support

### ISSUE THREAD

**Issue by Spl3en** [trezor/trezor-common#275]
Hello,

According to the [Developer guide in the Contributing section](https://wiki.trezor.io/Developers_guide:Contributing#Adding_a_new_coin), I'm posting this issue in order to discuss creating ICX support for Trezor. Many people holding ICX [are requesting it regularly](https://i.imgur.com/6kb0yY7.png) (for many months now).

* **What is the approximate scale?** 

Similar scale than the already supported ones.

* **Do we need any new cryptographic primitives to support this coin?**

ICON uses secp256k1 and SHA3, very similarly to Ethereum. So it should be supported easily by Trezor.

* **Is there (or will you develop) a frontend wallet that will support Trezor with this coin?**

There is no frontend wallet that supports Trezor right now. However, we have an official wallet (ICONex) supporting Ledger already. So, once the Trezor support is done, I suppose it can be added too, potentially.

Let me know what you think about it, so we can start working on it, thank you.

**Comment by matejcik** [comment]
does ICON need a completely new impl, or is it a fork of some already implemented currency (so that we could, e.g., extend Ethereum code with some parameter tweak to also sign ICON transactions)?

do you have developer docs regarding signature formats etc.?

**Comment by Spl3en** [comment]
Thanks for the answer @matejcik.
ICON is a completely new implementation. So it will require to code something new, however the cryptography is similar to Ethereum.

Here's a documentation about how to sign an ICON transaction : 
https://icondev.readme.io/docs/transaction-signature#section-create-transaction-signature

**Comment by matejcik** [comment]
thanks for the links. we will look into it and let you know.

**Comment by Spl3en** [comment]
Thanks, much appreciated.

**Comment by Spl3en** [comment]
Hey,
Is there any update about it ?
Thanks!

**Comment by prusnak** [comment]
Yes, you can start working on the integration. Start with adding messages to `protob` folder in this repo. Afterwards you can work on the code submitted to trezor-core.

**Comment by Spl3en** [comment]
@prusnak @matejcik Thanks!
Last question before I start coding it, can you confirm there is no difference in the protocol if I buy a Trezor One or a Trezor T model ? I need to buy a Trezor for testing but I don't know which one.

**Comment by prusnak** [comment]
@Spl3en trezor-core run on Trezor Model T. This will be later ported to Trezor One as well, but for now you need Model T. trezor-core also has an emulator, check the repo for more instructions.

**Comment by tomazcz** [comment]
@prusnak Is this still valid - would merge code for support of ICX?

Asking because of this:
> at this time we do not plan to add coins that are not in the Top 30 by market cap.

**Comment by matejcik** [comment]
yes, the Top 30 limit still applies
