### ISSUE TITLE
ETP(Metaverse Entropy) Support

### ISSUE THREAD

**Issue by Trinity163** [trezor/trezor-common#279]
Hello Trezor Team,

According to the [Developer guide in the Contributing section](https://wiki.trezor.io/Developers_guide:Contributing#Adding_a_new_coin), I'm posting this issue in order to discuss creating ETP support for Trezor. 

Metaverse is a blockchain project that provides a foundational infrastructure for social and enterprise needs. Our goal is to construct a universe where digital assets (Metaverse Smart Token) and digital identities (Avatar) build the basis for asset transactions with the help of a value intermediary (Oracle), thus establishing a new blockchain ecosystem that will transform human society and allow us to enter the New Reality.

Currently, it's ranked among the top 100 at [CMC](https://coinmarketcap.com/currencies/metaverse/), and has an excellent community environment.

* **What is the approximate scale?**

Similar scale as Bitcoin.

* **Do we need any new cryptographic primitives to support this coin?**

ETP uses secp256k1 and SHA3, very similar to Bitcoin. So it should be supported easily by Trezor.

* **Is there (or will you develop) a frontend wallet that will support Trezor with this coin?**

We have an official wallet (MyETPWallet) and many third-party wallets which support ETP transaction. Once the Trezor support is done, I suppose it can be added too, potentially.

Let me know what you think about it, so we can start working on it, thank you.

**Comment by matejcik** [comment]
can you please provide links to developer documentation?
esp. wrt:
* transaction format and signing
* address format

**Comment by Trinity163** [comment]
Hi matejcik,

Below is the documentation, please take a look!

https://docs.mvs.org/developers/mvs-transaction-format-and-signing.html
https://docs.mvs.org/developers/mvs-wallet-address-example.html

Best,
Trinity

**Comment by matejcik** [comment]
thank you.
AFAICT this is somewhat similar to OMNI layer? i.e., it's mostly Bitcoin with some additional data attached?

i didn't see any mention of SHA3 in the docs, did you mean Bitcoin's hashes, i.e., SHA256/RIPEMD160 ?

**Comment by Trinity163** [comment]
Hi matejcik,

Thanks for your prompt reply!
Yes, in addition to expanding the data, other technologies are consistent with Bitcoin. In fact, our source code comes from libbitcoin fork, the hash algorithm and signature algorithm used are consistent with Bitcoin as well.

The hash algorithm is based on SHA256/RIPEMD160.

Best,
Trinity

**Comment by Trinity163** [comment]
Hi matejcik,

How are you doing?
Any other things I can support you with?
Do let me know anytime when you have the needs, appreciated!

Best,
Trinity

**Comment by prusnak** [comment]
We don't want to add coins that do not belong to TOP 30 coins at the moment.
