### ISSUE TITLE
High Performance Blockchain (HPB) Support

### ISSUE THREAD

**Issue by TedNIVAN** [trezor/trezor-common#285]
Hello there,

Based on the developer guide, here is the information needed to get **High Performance Blockchain (HPB)** support for Trezor.

First of all, a quick overview about HPB:

> High Performance Blockchain (HPB) is a revolutionary permissionless blockchain architecture that combines an opensource Blockchain Offload Engine (BOE) hardware, with software optimized to work in tandem with the BOE unit. Using the synergy created by merging hardware and software, high transaction speeds and minimal latency is achieved with no compromises (e.g. security, decentralization, etc. are all conserved). This is achieved with HPB’s consensus algorithm where the network verifies transactions with an underlying dual Node election mechanism, striking a balance between voting and delegation.

More here: 

- http://hpb.io/
- http://open.hpb.io/#/about?id=8

### What is the approximate scale?
Similar scale than the already supported ones.

### Do we need any new cryptographic primitives to support this coin?
HPB uses **bn256**, **ecies**, **randentropy**, **secp256k1** and **sha3**.
You can check that out here: https://github.com/hpb-project/go-hpb/tree/master/common/crypto

**This pretty much similar to the Ethereum blockchain.**
You can compare here: https://github.com/ethereumproject/go-ethereum/tree/master/crypto

### Is there (or will you develop) a frontend wallet that will support Trezor with this coin?
We currently have no frontend wallet that supports Trezor.
However, this should be added to future development.

### Provide links to relevant developer documentation, esp. about address format and transaction signing
Address format: http://open.hpb.io/#/about?id=6

Transaction signing: 

- https://github.com/hpb-project/go-hpb/blob/14583a485b3106487560e58e2b6dfc2bea9c0ffa/internal/hpbapi/api.go
- https://github.com/hpb-project/go-hpb/blob/7c2438321b34f2daf87019d5e878b1798e49d586/blockchain/types/tx_signer.go

### Provide a link to a transaction explorer
Here it is: https://hpbscan.org/txs

Let me now if you need further information,

Kind regards, Ted NIVAN

**Comment by prusnak** [comment]
The biggest problem I see is the support of bn256, which is missing from trezor-crypto. If you manage to add C implementation of bn256 to [trezor-crypto}(https://github.com/trezor/trezor-crypto) it might be feasible to add the rest. So I suggest you start there.

**Comment by TedNIVAN** [comment]
Hi @prusnak,
Thanks for replying.

I'm going to reach out to the team and see if they have a C version of the Go implementation.
If not I will try to code it based on the [original paper](https://cryptojedi.org/papers/dclxvi-20100714.pdf) and the [documentation provided by GoDoc](https://godoc.org/golang.org/x/crypto/bn256).

I'll get back to you as soon as I can.

**Comment by TedNIVAN** [comment]
**It looks like Ethereum is using bn256 as well.**
https://github.com/ethereum/go-ethereum/tree/master/crypto/bn256

I wonder if that is really an issue because Trezor supports Ethereum.

**Comment by TedNIVAN** [comment]
Hello @prusnak, 

I've linked up with the **HPB Team** and they said it should not be a problem because **we do inherit from Ethereum**. 

Please tell me if you need more information.
Ted

**Comment by prusnak** [comment]
We don't want to add coins that do not belong to TOP 30 coins at the moment.
