### ISSUE TITLE
Ontology (ONT) Support

### ISSUE THREAD

**Issue by TedNIVAN** [trezor/trezor-common#286]
Hello there,

Based on the developer guide, here is the information needed to get **Ontology (ONT)** support for Trezor.

First of all, a quick overview about ONT:

> Ontology is a new high-performance public blockchain project & a distributed trust collaboration platform. Ontology provides new high-performance public blockchains that include a series of complete distributed ledgers and smart contract systems.

More here: 

- https://ont.io/

### What is the approximate scale?
Similar scale than the already supported ones.

### Do we need any new cryptographic primitives to support this coin?
ONT uses  **ECDSA**, **SM2**, and **ED25519**.

You can check that out here: 

- https://dev-docs.ont.io/#/docs-en/OntologyCli/04-wallet-management
- https://github.com/ontio/ontology-crypto

### Is there (or will you develop) a frontend wallet that will support Trezor with this coin?
We currently have no frontend wallet that supports Trezor.
However, this should be added to future development.

### Provide links to relevant developer documentation, esp. about address format and transaction signing
Address format: https://dev-docs.ont.io/#/docs-en/OntologyCli/04-wallet-management

Transaction signing: 

- https://dev-docs.ont.io/#/docs-en/OntologyCli/06-transactions?id=sign-transaction
- https://github.com/ontio/ontology/tree/06b54d720c33a34d145d256872aeef577801b49c/core/signature

### Provide a link to a transaction explorer
Here it is: https://explorer.ont.io/transactions/20/1

Let me now if you need further information,

Kind regards, Ted NIVAN

**Comment by prusnak** [comment]
Ontology is already implemented: https://github.com/trezor/trezor-core/pull/323

We just need to merge the PR

**Comment by TedNIVAN** [comment]
Okay I wasn't really sure. Thank you @prusnak.
