### ISSUE TITLE
trezor-udev

### ISSUE THREAD

**Issue by hegjon** [trezor/trezor-common#30]
Hi, I noticed that you build RPMS for trezor-udev, is this a package you would like to include in Fedora (and EPEL for CentOS), now this file is bundled with python-trezor RPM.

**Comment by prusnak** [comment]
I think it would be fine to just branch trezor-udev package from python-trezor as its subpackage and add trezor-udev as a requirement for installing python-trezor

**Comment by hegjon** [comment]
How is this file versioned?

**Comment by prusnak** [comment]
It's not

**Comment by hegjon** [comment]
Do you think I should go for version 0? https://fedoraproject.org/wiki/Packaging:Versioning#Upstream_has_never_chosen_a_version

**Comment by prusnak** [comment]
Yes, please

**Comment by hegjon** [comment]
Great, what is the license?

**Comment by prusnak** [comment]
Let's use the same as python-trezor to not complicate things: LGPL-3.0+

**Comment by hegjon** [comment]
Great, I plan to name it trezor-common and also include the protobuf message

**Comment by hegjon** [comment]
Do you mind adding a license file at the project root?

**Comment by prusnak** [comment]
Added license in https://github.com/trezor/trezor-common/commit/9e7922d61a6a40a2c9b23a7e7f95db488848bb3d

**Comment by hegjon** [comment]
Thanks

**Comment by hegjon** [comment]
Package have been reviewed and approved, will probably be in the stable Fedora repository in 2 weeks. https://bugzilla.redhat.com/show_bug.cgi?id=1464797
