### ISSUE TITLE
BCN Support

### ISSUE THREAD

**Issue by bcndev** [trezor/trezor-common#306]
Hello there,

Based on the developer guide, we would like to provide you with the information needed to get Bytecoin (BCN) support for Trezor.

A quick overview about Bytecoin:

> Bytecoin is a private decentralized cryptocurrency with an open source code, the first implementation of the CryptoNote Protocol.

And more here: https://bytecoin.org

## What is the approximate scale?
Similar scale that the already supported coins.

## Do we need any new cryptographic primitives to support this coin?

We use crypto similar but simpler than Monero. We need no changes in `trezor-crypto` repository. Although we will have to add a wrapper to the `embed/extmod/modtrezorcrypto` module.

## Is there (or will you develop) a frontend wallet that will support Trezor with this coin?

Our current cross-platform Desktop client is ready to support the Trezor wallet.

## Provide links to relevant developer documentation, esp. about address format and transaction signing.

We use CryptoNote address format with two prefices `6` and `572238`. The two address types look like this

* `21UQFLdH7WvPZEd8HNwXncHtDwFvv4GRqaN3R4cWyuw2TRZxRtRPb7FFTxfcwwQsqYSD2EqhgVCLsGdRdejAoHFHAHJrxxo`
* `bcnZ6VSM78fQNL5js7VnCybbs3ojLbdAD4DfbdJkUqghYWLqXeEgdyo9UyiAZKnB548DK1ofu8wed3jYCPT62zpf2R97SejoT7`

As to our signing scheme, we implement averagely complicated interactive scheme like Monero (yet with much less code).

More info can be reached at https://github.com/bcndev/bytecoin/wiki

## Provide a link to a transaction explorer

https://explorer.bytecoin.org

We are looking forward to any questions or comments to make the support happen.

Best regards,
The Bytecoin Team

**Comment by prusnak** [comment]
Let's not add coins unless they are in the top 30 of coinmarketcap.

**Comment by LouisWayne** [comment]
No!!! Can you please reconsider the changes? I really want this so badly 😢
