### ISSUE TITLE
Adding BitShares support 

### ISSUE THREAD

**Issue by Adman** [trezor/trezor-common#311]
* What is the approximate scale?
We would like to add just `getPublicKey` and simple `transfer` operations and maybe extend it to support more operations in the future.

* Do we need any new cryptographic primitives to support this coin?
No, we just need to add `is_canonical` function when signing with secp256k1.

* BitShares docs: http://docs.bitshares.org/

* Pybitshares docs: http://docs.pybitshares.com

* Signing transaction: http://docs.pybitshares.com/en/latest/bitsharesbase.signedtransactions.html#bitsharesbase.signedtransactions.Signed_Transaction.sign

* Explorer: https://bitshares-explorer.io

**Comment by prusnak** [comment]
We don't want to add coins that do not belong to TOP 30 coins at the moment.
