### ISSUE TITLE
QTUM support

### ISSUE THREAD

**Issue by pandazwb** [trezor/trezor-common#323]
Hi Trezor team,

We have added Qtum support in related Trezor repos, and all changes seem to be merged already. But yet the coin status on your website https://trezor.io/coins/ for QTUM is still "Soon":

![image](https://user-images.githubusercontent.com/4017213/56715500-75ad5980-676a-11e9-8122-2e4a0649d66c.png)

What extra actions are required from Qtum to make it fully "supported" on Trezor?

**Comment by prusnak** [comment]
It will be supported in the next firmware update.
