### ISSUE TITLE
MAN Support

### ISSUE THREAD

**Issue by MatrixAINetworkMan** [trezor/trezor-common#324]
Hello there, According to the Developer guide in the Contributing section, we would like to provide you with the information needed to get MATRIXAINETWORK (MAN) support for Trezor.

### A quick overview about MATRIXAINETWORK

MATRIX AI Network is an intelligent new generation blockchain that aims to solve major challenges currently stifling the development and adpotion of block-chain technology

And more here: https://www.matrix.io/

### What is the approximate scale?
+ Similar scale than the already supported ones.

### Do we need any new cryptographic primitives to support this coin?
+ MATRIX uses secp256k1 and SHA3, very similarly to Ethereum. So it should be supported easily by Trezor.

### Is there (or will you develop) a frontend wallet that will support Trezor with this coin?
+ We currently have no frontend wallet that supports Trezor.
However, this should be added to future development.

### Provide links to relevant developer documentation, esp. about address format and transaction signing

+ Address format: https://github.com/MatrixAINetwork/TxSend-Sign-Demos/blob/master/Address%20Format.md

+ Transaction signing:

JS: https://github.com/MatrixAINetwork/TxSend-Sign-Demos/tree/master/js

Golang: https://github.com/MatrixAINetwork/TxSend-Sign-Demos/tree/master/go

### Provide a link to a transaction explorer
+ https://tom.matrix.io/

**Comment by matejcik** [comment]
thanks for your interest.
at this time we do not plan to add coins that are not in the Top 30 by market cap.
