### ISSUE TITLE
Protobuf 'Option "deprecated" unknown.'

### ISSUE THREAD

**Issue by achow101** [trezor/trezor-common#34]
I get a `Option "deprecated" unknown.` error when trying to compile `messages.proto`

**Comment by saleemrashid** [comment]
Which compiler are you using?

**Comment by achow101** [comment]
protoc 3.3.0

**Comment by hegjon** [comment]
Protonbuf2 does not support the deprecated option, a quick fix I use when I build with protobuf2:
`sed -i 's/, deprecated = true//g' protob/messages.proto`

**Comment by prusnak** [comment]
Works for me using protoc 3.1.0 and protoc 3.3.0.

If you are using Linux report this to your distribution maintainer.

**Comment by achow101** [comment]
I'm using the official release binaries provided by Google...

**Comment by prusnak** [comment]
Report it to Google then or use the suggestion from hegjon above.

**Comment by prusnak** [comment]
I would start here: https://github.com/google/protobuf/issues/1734
