### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by almindor** [trezor/trezor-common#41]
Can you please create releases? Just major change versions should be fine. This will help a lot with packaging for linux where git submodules are hard to do (or impossible due to packaging rules).

**Comment by saleemrashid** [comment]
To me, it doesn't make sense to version it. Protocol Buffers don't need versioning. It is useless and possibly dangerous to use an outdated `coins.json`. There have been no breaking changes in the udev rules or the `config.json` AFAIK.

**Comment by almindor** [comment]
This is not really about std. usage but more about packaging.

In my case I'm trying to package Etherwall which uses trezor-common as a submodule into Arch linux AUR.

The standard way of handling sources in AUR is to have an external source checked through a hash.

I can point to your master.tar.gz link but if you do any change and a new commit goes in, the hash won't fit anymore and the build will fail, completely outside of my control.

I could just use git directly but many people/package managers (as in admins) look down on this as there's no hash checking of the full source (even tho you can checkout a specific commit, someone could e.g. attack the source version control server).

So right now I have to go around the source-hashing standards. It'd just be much easier if I can point to a specific version and say this version of trezor-common is used in this version of Etherwall.

**Comment by saleemrashid** [comment]
> I can point to your master.tar.gz link but if you do any change and a new commit goes in, the hash won't fit anymore and the build will fail, completely outside of my control.

Just so you know, GitHub's archive URL supports any commit notiation, not just symbol references. The following are all equivalent (at the time of writing):

https://github.com/trezor/trezor-common/archive/5f7a1a7.tar.gz
https://github.com/trezor/trezor-common/archive/5f7a1a7a5a4311fd71ed113624dd1d0fe9e72ff5.tar.gz
https://github.com/trezor/trezor-common/archive/HEAD^.tar.gz
https://github.com/trezor/trezor-common/archive/master~1.tar.gz

> I could just use git directly but many people/package managers (as in admins) look down on this 

I would be interested in any examples of this.

> no hash checking of the full source (even tho you can checkout a specific commit, someone could e.g. attack the source version control server).

There's SHA-1 checking of the source, by virtue of checking out a specific commit so you couldn't attack the VCS server. And to be even more paranoid, Arch Linux obviously has a newer Git version than 2.13, so the known attacks against SHA-1 are prevented.

**Comment by almindor** [comment]
Didn't know about the commit hash archiving, will use that then. Thanks.
