### ISSUE TITLE
Address Prefixes (bitcoin: variants)

### ISSUE THREAD

**Issue by ch4ot1c** [trezor/trezor-common#94]
Hi there -

I am currently working on a payments platform, and have been deep into BIP-0070 - BIP-0073 specification. These are all defined for `bitcoin:` only, however I see that `address_prefix` varies depending on the currency.

I have always preferred this variability, but understand that it could be a security concern. Mozilla web documentation only approves the `bitcoin` scheme: 
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

Where do we go from here? A SLIP?

Thank you

**Comment by prusnak** [comment]
I would just say that https://github.com/trezor/trezor-common/blob/master/coins.json is a canonical source for this for now.
